export const SA_CITIES = [
  'Albany / Grahamstown (Makhanda)',
  'Aliwal North',
  'Beaufort West',
  'Bellville',
  'Benoni',
  'Bethlehem',
  'Bhisho / King William\'s Town',
  'Bloemfontein',
  'Boksburg',
  'Brakpan',
  'Brits',
  'Cape Town',
  'Centurion',
  'Chatsworth',
  'De Aar',
  'Durban',
  'East London',
  'Ekurhuleni (East Rand)',
  'eMalahleni (Witbank)',
  'Empangeni',
  'Germiston',
  'George',
  'Harrismith',
  'Hartbeespoort',
  'Heidelberg (GP)',
  'Hermanus',
  'Johannesburg CBD',
  'Kathu',
  'Kimberley',
  'Klerksdorp',
  'Knysna',
  'Kokstad',
  'Kroonstad',
  'Krugersdorp',
  'KwaDukuza (Stanger)',
  'Ladysmith',
  'Langebaan',
  'Lichtenburg',
  'Louis Trichardt (Makhado)',
  'Mafikeng (Mahikeng)',
  'Margate',
  'Mbombela (Nelspruit)',
  'Midrand',
  'Middelburg (EC)',
  'Middelburg (MP)',
  'Mitchell\'s Plain',
  'Mossel Bay',
  'Mthatha (Umtata)',
  'Musina',
  'Newcastle',
  'Oudtshoorn',
  'Paarl',
  'Phalaborwa',
  'Phuthaditjhaba',
  'Pietermaritzburg',
  'Pinetown',
  'Polokwane',
  'Port Elizabeth (Gqeberha)',
  'Port Shepstone',
  'Potchefstroom',
  'Pretoria',
  'Queenstown (Komani)',
  'Randburg',
  'Richards Bay',
  'Roodepoort',
  'Rustenburg',
  'Sandton',
  'Sasolburg',
  'Secunda',
  'Somerset West',
  'Soweto',
  'Springs',
  'Standerton',
  'Stellenbosch',
  'Tembisa',
  'Thohoyandou',
  'Tongaat',
  'Tzaneen',
  'Umhlanga',
  'Upington',
  'Vanderbijlpark / Vereeniging',
  'Welkom',
  'Worcester',
];
